import { Command } from "commander";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";
import chalk from "chalk";

const MARKER = "// ============================================================\n// START THE SERVER";

function getIndexPath(): string {
  const path = join(process.cwd(), "src", "index.ts");
  if (!existsSync(path)) {
    console.error(
      chalk.red("Error: src/index.ts not found. Are you in an MCP server project?")
    );
    process.exit(1);
  }
  return path;
}

function injectCode(code: string): void {
  const indexPath = getIndexPath();
  const content = readFileSync(indexPath, "utf-8");

  if (!content.includes(MARKER)) {
    console.error(
      chalk.red(
        "Error: Could not find the server startup section in src/index.ts.\n" +
        "Make sure the file was generated by mcp-craft."
      )
    );
    process.exit(1);
  }

  const updated = content.replace(MARKER, code + "\n" + MARKER);
  writeFileSync(indexPath, updated);
}

function addTool(name: string): void {
  const camelName = name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

  const code = `server.tool(
  "${name}",
  "TODO: describe what ${name} does",
  {
    // TODO: define your input parameters using Zod
    input: z.string().describe("TODO: describe this parameter"),
  },
  async ({ input }) => {
    // TODO: implement your tool logic here
    return {
      content: [{ type: "text", text: \`${camelName} result: \${input}\` }],
    };
  }
);

`;

  injectCode(code);
  console.log(chalk.green(`\n✓ Added tool "${name}" to src/index.ts`));
  console.log(chalk.dim("  Edit the TODO comments to implement your tool.\n"));
}

function addResource(name: string): void {
  const uri = `${name}://data`;

  const code = `server.resource(
  "${name}",
  "${uri}",
  {
    description: "TODO: describe what ${name} provides",
    mimeType: "application/json",
  },
  async (uri: URL) => ({
    contents: [
      {
        uri: uri.href,
        mimeType: "application/json",
        text: JSON.stringify({
          // TODO: return your resource data here
          message: "Hello from ${name}",
        }, null, 2),
      },
    ],
  })
);

`;

  injectCode(code);
  console.log(chalk.green(`\n✓ Added resource "${name}" to src/index.ts`));
  console.log(chalk.dim("  Edit the TODO comments to implement your resource.\n"));
}

function addPrompt(name: string): void {
  const code = `server.prompt(
  "${name}",
  "TODO: describe what ${name} does",
  {
    // TODO: define your prompt arguments using Zod
    input: z.string().describe("TODO: describe this parameter"),
  },
  ({ input }) => ({
    messages: [
      {
        role: "user" as const,
        content: {
          type: "text" as const,
          // TODO: craft your prompt message
          text: \`${name}: \${input}\`,
        },
      },
    ],
  })
);

`;

  injectCode(code);
  console.log(chalk.green(`\n✓ Added prompt "${name}" to src/index.ts`));
  console.log(chalk.dim("  Edit the TODO comments to implement your prompt.\n"));
}

export const addCommand = new Command("add")
  .description("Add a tool, resource, or prompt to your MCP server")
  .argument("<type>", "What to add: tool, resource, or prompt")
  .argument("<name>", "Name for the new tool/resource/prompt")
  .action((type: string, name: string) => {
    switch (type) {
      case "tool":
        addTool(name);
        break;
      case "resource":
        addResource(name);
        break;
      case "prompt":
        addPrompt(name);
        break;
      default:
        console.error(
          chalk.red(`Unknown type "${type}". Use: tool, resource, or prompt`)
        );
        process.exit(1);
    }
  });
